# render.yaml

# Versión de la configuración de Render
version: 1.1

services:
  - name: web
    buildCommand: npm install --production
    startCommand: npm start
    env:
      NODE_ENV: production
    healthCheckPath: /
    logConfig:
      level: debug
      destination: console
